In [1]:
import sys, os
cwd = os.getcwd()
print(cwd)
sys.path.insert(0, os.path.join(cwd, '..'))

/home/leonhard/Projects/AtlasOfSmoothSpaces/GestureLab/MpHandsRtclear/notebooks


In [2]:
from segmentation.trainModel import Training

In [3]:
tr = Training()

### Try to retrieve a youtube clip

In [5]:
rawMotionBankCSVPath = "../parseannotations/csv/motionbank_test.csv"
df_filtered, parseddict = tr.getFilteredDataFrame(
    rawMotionBankCSVPath=rawMotionBankCSVPath,
    landmarkFileName="testLMFN.csv",
    fromRoot=False,
    saveOutputToCSV=True)

You chose to parse the annotations corresponding to 'video1':
{'name': 'https://youtu.be/gjCHOGdPIR8', 'by': 'Adrián Artacho', 'from': 0.0, 'till': 4.0}
Annotations earlier than 0.0 and later than 4.0 will be removed.
All annotation times will be offset by 0.0 seconds.
You chose to process annotations by Adrián Artacho.
('annotation1', {'name': 'hello', 'by': 'Adrián Artacho', 'from': 0.0, 'till': 1.9500000476837158})
('annotation2', {'name': 'bye', 'by': 'Adrián Artacho', 'from': 1.9500000476837158, 'till': 1.9500000476837158})
['nose', 'left_eye_inner', 'left_eye', 'left_eye_outer', 'right_eye_inner', 'right_eye', 'right_eye_outer', 'mouth_left', 'mouth_right', 'left_shoulder', 'right_shoulder', 'left_elbow', 'right_elbow', 'left_wrist', 'right_wrist', 'left_pinky_1', 'right_pinky_1', 'left_index_1', 'right_index_1', 'left_thumb_2', 'right_thumb_2', 'left_hip', 'right_hip', 'left_knee', 'right_knee', 'left_ankle', 'right_ankle', 'left_heel', 'right_heel', 'left_foot_index', 'right_fo

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.


Ignoring empty frame.


In [6]:
ex = ['a','c','b']

In [7]:
ex.sort(reverse=False)

#### Check Model training and pickles

In [34]:
kwargs = dict(
        rawMotionBankCSVPath="../parseannotations/csv/motionbank_test.csv",
        landmarkFileName="exampleblaa",
        fromCache=True,
        fromRoot=False,
        saveOutputToCSV=True)
newKwargs = dict(**kwargs,  batch_size=3)
        # print(newKwargs)
res = tr.generateDataFromPieceMaker(**newKwargs)

You chose to parse the annotations corresponding to 'video1':
{'name': 'https://youtu.be/gjCHOGdPIR8', 'by': 'Adrián Artacho', 'from': 0.0, 'till': 4.0}
Annotations earlier than 0.0 and later than 4.0 will be removed.
All annotation times will be offset by 0.0 seconds.
You chose to process annotations by Adrián Artacho.
('annotation1', {'name': 'hello', 'by': 'Adrián Artacho', 'from': 0.0, 'till': 1.9500000476837158})
('annotation2', {'name': 'bye', 'by': 'Adrián Artacho', 'from': 1.9500000476837158, 'till': 1.9500000476837158})
['left_hip', 'right_hip']
data [ 1.18707961 11.08009677  7.66685914 -1.21606006 11.02647121  8.49492238]
length of data 6 
3batchsize 9
data [ 1.18707961 11.08009677  7.66685914 -1.21606006 11.02647121  8.49492238
  1.19340398 11.24147409  8.19995551 -1.22215313 11.2525996   9.23044958]
length of data 12 
3batchsize 9
data [ 1.18707961 11.08009677  7.66685914 -1.21606006 11.02647121  8.49492238
  1.19340398 11.24147409  8.19995551 -1.22215313 11.2525996   9.230

In [37]:
len(res[0])

18

In [39]:
tr.fitModel(n_components=2, data=res)

In [10]:
tr.pickleModel()

In [11]:
tr2 = Training()

In [12]:
tr2.pickle = "somewhere.pickle"

In [13]:
tr2.loadGMM()

In [40]:
Y = res * 1.2 + 0.2

In [17]:
len(Y)

57

In [41]:
tr.gmm.predict(res)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
means = tr.gmm.means_
len(means)

2

In [59]:
import numpy as np


array([[ 1.26776351, 10.63576861,  5.42806812, -0.98607057, 10.61296738,
         6.48363598],
       [ 1.27011835, 10.64116869,  5.39240109, -0.9806226 , 10.62078687,
         6.45556132],
       [ 1.27260578, 10.65148725,  5.36467895, -0.97646264, 10.63339534,
         6.43443379]])

In [61]:
threesnapshots = np.reshape(means[0], (3,6))
print("The movement pattern consists of three consecutive positions of the hip\n\n")
for i, snapshot in enumerate(threesnapshots):
    left_hip = snapshot[0:3]
    right_hip = left_hip = snapshot[3:]
    print(f"The {i}-th time the position of the left hip is:\n {repr(left_hip)}\n and of the right hip \n{repr(right_hip)}.\n")

The movement pattern consists of three consecutive positions of the hip


The 0-th time the position of the left hip is:
 array([-0.98607057, 10.61296738,  6.48363598])
 and of the right hip 
array([-0.98607057, 10.61296738,  6.48363598]).

The 1-th time the position of the left hip is:
 array([-0.9806226 , 10.62078687,  6.45556132])
 and of the right hip 
array([-0.9806226 , 10.62078687,  6.45556132]).

The 2-th time the position of the left hip is:
 array([-0.97646264, 10.63339534,  6.43443379])
 and of the right hip 
array([-0.97646264, 10.63339534,  6.43443379]).

